version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always 
    ports:
      - '27017:27017'
    volumes:
      - MongoCollections:/data/db
  mongo_seed:
    build: ./seed
    depends_on:
      - mongo
  app:
    container_name: grooming_back_end__container
    image: grooming_back_end_image
    volumes:
      - .:/app
    restart: unless-stopped
    build: .
    ports:
      - '4000:3000'
    depends_on:
      - mongo
  
volumes:
  MongoCollections:
    external: false