version: '3'
services:
  app:
    container_name: grooming_back_end__container
    image: grooming_back_end_image
    volumes:
      - .:/app
    restart: no
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always 
    ports:
      - '27017:27017'